# Generated by Django 6.0.4 on 2026-05-30 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Hayvon nomi",
                    ),
                ),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("dog", "It"),
                            ("cat", "Mushuk"),
                            ("cow", "Sigir"),
                            ("horse", "Ot"),
                            ("sheep", "Qo‘y"),
                            ("goat", "Echki"),
                            ("bird", "Qush"),
                            ("other", "Boshqa"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="Hayvon turi",
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Zoti"
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Yoshi"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Erkak"),
                            ("female", "Urg‘ochi"),
                            ("unknown", "Noma’lum"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Jinsi",
                    ),
                ),
                (
                    "symptoms",
                    models.TextField(
                        blank=True, null=True, verbose_name="Kasallik belgilari"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animals",
                        to="accounts.client",
                        verbose_name="Mijoz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hayvon",
                "verbose_name_plural": "Hayvonlar",
                "ordering": ["-created_at"],
            },
        ),
    ]
