# Generated by Django 6.0.4 on 2026-05-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="animal_code",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Hayvon ID",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="animal_type",
            field=models.CharField(
                choices=[
                    ("dog", "It"),
                    ("cat", "Mushuk"),
                    ("cow", "Mol"),
                    ("horse", "Ot"),
                    ("sheep", "Qo‘y"),
                    ("goat", "Echki"),
                    ("bird", "Qush / Parranda"),
                    ("other", "Boshqa"),
                ],
                default="other",
                max_length=30,
                verbose_name="Hayvon turi",
            ),
        ),
    ]
