# Generated by Django 6.0.4 on 2026-05-30 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DangerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "danger_type",
                    models.CharField(
                        choices=[
                            ("dead_animal", "O‘lik hayvon"),
                            ("lifeless_animal", "Jonsiz hayvon"),
                            (
                                "aggressive_animal",
                                "Quturgan yoki tajovuzkor hayvon gumoni",
                            ),
                            ("infectious_disease", "Yuqumli kasallik gumoni"),
                            ("other", "Boshqa xavfli holat"),
                        ],
                        max_length=50,
                        verbose_name="Xavf turi",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Qo‘shimcha ma’lumot"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Telefon raqam",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Manzil"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Kenglik",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Uzunlik",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("reviewed", "Ko‘rib chiqildi"),
                            ("in_progress", "Chora ko‘rilmoqda"),
                            ("completed", "Yakunlandi"),
                            ("rejected", "Rad etildi"),
                        ],
                        default="new",
                        max_length=30,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Administrator izohi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="danger_reports",
                        to="accounts.client",
                        verbose_name="Xabar yuborgan mijoz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xavfli holat xabari",
                "verbose_name_plural": "Xavfli holatlar xabarlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("clinic", "Klinikada davolash"),
                            ("vet_call", "Veterinar chaqirish"),
                        ],
                        max_length=30,
                        verbose_name="Xizmat turi",
                    ),
                ),
                (
                    "problem_description",
                    models.TextField(verbose_name="Muammo tavsifi"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Manzil"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Kenglik",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Uzunlik",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("accepted", "Qabul qilindi"),
                            ("in_progress", "Jarayonda"),
                            ("completed", "Yakunlandi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="new",
                        max_length=30,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Administrator izohi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to="animals.animal",
                        verbose_name="Hayvon",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to="accounts.client",
                        verbose_name="Mijoz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat arizasi",
                "verbose_name_plural": "Xizmat arizalari",
                "ordering": ["-created_at"],
            },
        ),
    ]
