# Generated by Django 6.0.4 on 2026-05-30 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        ("requests_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dangerreport",
            name="assigned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Biriktirilgan vaqt"
            ),
        ),
        migrations.AddField(
            model_name="dangerreport",
            name="assigned_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_danger_reports",
                to="dashboard.doctorprofile",
                verbose_name="Biriktirilgan mas’ul",
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="assigned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Biriktirilgan vaqt"
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="assigned_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_service_requests",
                to="dashboard.doctorprofile",
                verbose_name="Biriktirilgan veterinar",
            ),
        ),
        migrations.AlterField(
            model_name="dangerreport",
            name="danger_type",
            field=models.CharField(
                choices=[
                    ("dead_animal", "O‘lik hayvon"),
                    ("aggressive_animal", "Quturgan yoki tajovuzkor hayvon gumoni"),
                    ("infectious_disease", "Yuqumli kasallik gumoni"),
                    ("other", "Boshqa xavfli holat"),
                ],
                max_length=50,
                verbose_name="Xavf turi",
            ),
        ),
        migrations.AlterField(
            model_name="dangerreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Yangi xavfli holat"),
                    ("reviewed", "Ko‘rib chiqildi"),
                    ("assigned", "Mas’ul biriktirildi"),
                    ("in_progress", "Chora ko‘rilmoqda"),
                    ("completed", "Yakunlandi"),
                    ("rejected", "Rad etildi"),
                ],
                default="new",
                max_length=30,
                verbose_name="Holati",
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Yangi"),
                    ("accepted", "Qabul qilindi"),
                    ("assigned", "Veterinarga biriktirildi"),
                    ("in_progress", "Jarayonda"),
                    ("completed", "Yakunlandi"),
                    ("cancelled", "Bekor qilindi"),
                ],
                default="new",
                max_length=30,
                verbose_name="Holati",
            ),
        ),
    ]
