# Generated by Django 6.0.4 on 2026-05-30 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("requests_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("created", "Yaratildi"),
                            ("status_changed", "Status o‘zgartirildi"),
                            ("assigned", "Mas’ul biriktirildi"),
                            ("comment_added", "Izoh qo‘shildi"),
                            ("completed", "Yakunlandi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        max_length=30,
                        verbose_name="Harakat turi",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Oldingi status",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Yangi status",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Izoh"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "danger_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="requests_app.dangerreport",
                        verbose_name="Xavfli holat xabari",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="requests_app.servicerequest",
                        verbose_name="Xizmat arizasi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_action_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harakat tarixi",
                "verbose_name_plural": "Harakatlar tarixi",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="F.I.Sh")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Telefon raqam",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Mutaxassislik",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("chief_vet", "Bosh veterinar"),
                            ("vet", "Veterinar"),
                            ("assistant", "Yordamchi xodim"),
                            ("danger_staff", "Xavfli holatlar bo‘yicha mas’ul"),
                        ],
                        default="vet",
                        max_length=30,
                        verbose_name="Lavozim",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "Bo‘sh"),
                            ("in_clinic", "Klinikada"),
                            ("on_service", "Xizmatda"),
                            ("busy", "Band"),
                            ("inactive", "Faol emas"),
                        ],
                        default="free",
                        max_length=30,
                        verbose_name="Holati",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veterinar profili",
                "verbose_name_plural": "Veterinar profillari",
                "ordering": ["full_name"],
            },
        ),
    ]
