# Generated by Django 6.0.4 on 2026-05-30 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="actionlog",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_logs",
                to="dashboard.doctorprofile",
                verbose_name="Biriktirilgan xodim",
            ),
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dashboard_action_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Harakatni bajargan foydalanuvchi",
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("chief_vet", "Bosh veterinar"),
                    ("vet", "Veterinar"),
                    ("responsible", "Mas’ul xodim"),
                    ("assistant", "Yordamchi xodim"),
                ],
                default="vet",
                max_length=30,
                verbose_name="Lavozim",
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("free", "Bo‘sh"),
                    ("busy", "Band"),
                    ("on_service", "Chaqiruvda"),
                    ("in_clinic", "Klinikada"),
                    ("inactive", "Faol emas"),
                ],
                default="free",
                max_length=30,
                verbose_name="Holati",
            ),
        ),
    ]
