# Generated by Django 6.0.4 on 2026-05-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_code",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Mijoz ID",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="F.I.Sh"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Telefon raqam"
            ),
        ),
    ]
